#!/usr/bin/env swift
// Deterministic synthetic-schema generator used to produce the "large" and
// "xlarge" fixtures under Examples/. Layout is stress-oriented, not
// production-realistic — many small tables + many indexes + a mix of
// short-hop and long-hop foreign keys.
//
// Usage:
//   swift Examples/tools/generate_synthetic.swift <numTables> <fanoutFKs> <outputPath>
//
// Example:
//   swift Examples/tools/generate_synthetic.swift 120 2 Examples/03-large-erp.postgres.sql
//   swift Examples/tools/generate_synthetic.swift 300 3 Examples/04-xlarge-hospital.postgres.sql

import Foundation

guard CommandLine.arguments.count >= 4,
      let n = Int(CommandLine.arguments[1]),
      let fk = Int(CommandLine.arguments[2]) else {
    FileHandle.standardError.write(Data("usage: generate_synthetic.swift <tables> <fkPerTable> <output>\n".utf8))
    exit(64)
}
let outPath = CommandLine.arguments[3]

// Seeded LCG so the generator is deterministic across runs.
struct SeededRNG: RandomNumberGenerator {
    var state: UInt64
    mutating func next() -> UInt64 {
        state = state &* 6364136223846793005 &+ 1442695040888963407
        return state
    }
}
var rng = SeededRNG(state: 0x53514c53434845)

// Realistic-ish domain vocabulary reused round-robin.
let domains = [
    "billing","catalog","inventory","hr","finance","crm","support","logistics",
    "audit","reporting","identity","payments","messaging","documents","calendar",
    "healthcare","insurance","research","content","analytics","procurement",
    "warehouse","fleet","maintenance","legal","compliance","marketing","training",
    "vendor","product","order","shipment","license","policy","facility","room",
    "asset","booking","survey","campaign","ticket","incident","request","batch",
    "lot","serial","voucher","credit","invoice","payment","refund","claim","chart",
    "lab","imaging","prescription","dose","patient","provider","practitioner",
    "encounter","diagnosis","procedure","observation","specimen","allergy",
    "immunization","medication","appointment","referral","authorization",
    "coverage","enrollment","member","dependent"
]
let noun = [
    "account","item","record","entry","event","log","note","tag","label","status",
    "type","category","group","batch","transaction","transfer","allocation",
    "assignment","reservation","booking","subscription","session","token","key",
    "role","permission","policy","plan","tier","level","stage","step","task",
    "attachment","comment","reaction","reminder","notification","preference"
]
let columnNames = [
    "name","description","code","external_id","status","kind","priority","score",
    "amount_cents","quantity","unit","weight_grams","started_at","ended_at",
    "notes","payload","metadata","reference"
]

func tableName(_ index: Int) -> String {
    let d = domains[index % domains.count]
    let n = noun[(index / domains.count) % noun.count]
    let suffix = (index / (domains.count * noun.count))
    return suffix == 0 ? "\(d)_\(n)" : "\(d)_\(n)_\(suffix)"
}

var out = ""
out.append("""
-- =====================================================================
-- Synthetic schema generated by Examples/tools/generate_synthetic.swift
-- Tables: \(n) · FK fan-out per table: up to \(fk) · Deterministic seed.
-- Layout is intentionally busy — a stress fixture for parser, layout,
-- and rendering performance.
-- =====================================================================

BEGIN;


""")

// Reserve names so FKs can reference tables created earlier.
let tables = (0..<n).map { tableName($0) }

for i in 0..<n {
    let name = tables[i]
    let extraCols = Int.random(in: 2...6, using: &rng)
    var columns: [String] = ["id           BIGSERIAL PRIMARY KEY"]
    for _ in 0..<extraCols {
        let base = columnNames.randomElement(using: &rng)!
        let typ: String
        switch Int.random(in: 0...5, using: &rng) {
        case 0: typ = "TEXT"
        case 1: typ = "INTEGER NOT NULL DEFAULT 0"
        case 2: typ = "BIGINT"
        case 3: typ = "NUMERIC(12,2)"
        case 4: typ = "BOOLEAN NOT NULL DEFAULT false"
        default: typ = "TIMESTAMPTZ NOT NULL DEFAULT now()"
        }
        // Suffix to avoid duplicates on the same table
        columns.append("\(base)_\(columns.count) \(typ)")
    }
    // FKs referencing earlier tables.
    let fkCount = min(fk, i)
    var fkTargets = Set<Int>()
    while fkTargets.count < fkCount {
        // Prefer near neighbours to create short-hop edges plus a few long-hops.
        let target: Int
        if Bool.random(using: &rng) && i > 5 {
            target = Int.random(in: max(0, i - 5)..<i, using: &rng)
        } else {
            target = Int.random(in: 0..<i, using: &rng)
        }
        fkTargets.insert(target)
    }
    var fkLines: [String] = []
    var indexLines: [String] = []
    for t in fkTargets.sorted() {
        let refName = tables[t]
        let col = "\(refName)_id"
        columns.append("\(col) BIGINT REFERENCES \(refName)(id)")
        fkLines.append("")
        _ = fkLines
        indexLines.append("CREATE INDEX \(name)_\(col)_idx ON \(name)(\(col));")
    }
    out.append("CREATE TABLE \(name) (\n")
    out.append("  " + columns.joined(separator: ",\n  ") + "\n")
    out.append(");\n")
    for l in indexLines { out.append(l); out.append("\n") }
    out.append("\n")
}

out.append("COMMIT;\n")

try out.write(toFile: outPath, atomically: true, encoding: .utf8)
FileHandle.standardOutput.write(Data("Wrote \(n) tables to \(outPath)\n".utf8))
