-- =====================================================================
-- Synthetic schema generated by Examples/tools/generate_synthetic.swift
-- Tables: 120 · FK fan-out per table: up to 2 · Deterministic seed.
-- Layout is intentionally busy — a stress fixture for parser, layout,
-- and rendering performance.
-- =====================================================================

BEGIN;

CREATE TABLE billing_account (
  id           BIGSERIAL PRIMARY KEY,
  metadata_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  amount_cents_2 NUMERIC(12,2),
  metadata_3 BIGINT,
  metadata_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  description_5 TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE catalog_account (
  id           BIGSERIAL PRIMARY KEY,
  unit_1 INTEGER NOT NULL DEFAULT 0,
  payload_2 BIGINT,
  billing_account_id BIGINT REFERENCES billing_account(id)
);
CREATE INDEX catalog_account_billing_account_id_idx ON catalog_account(billing_account_id);

CREATE TABLE inventory_account (
  id           BIGSERIAL PRIMARY KEY,
  notes_1 BIGINT,
  name_2 NUMERIC(12,2),
  description_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at_4 BIGINT,
  kind_5 BIGINT,
  started_at_6 BOOLEAN NOT NULL DEFAULT false,
  billing_account_id BIGINT REFERENCES billing_account(id),
  catalog_account_id BIGINT REFERENCES catalog_account(id)
);
CREATE INDEX inventory_account_billing_account_id_idx ON inventory_account(billing_account_id);
CREATE INDEX inventory_account_catalog_account_id_idx ON inventory_account(catalog_account_id);

CREATE TABLE hr_account (
  id           BIGSERIAL PRIMARY KEY,
  description_1 NUMERIC(12,2),
  payload_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  amount_cents_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  quantity_5 TEXT,
  amount_cents_6 BOOLEAN NOT NULL DEFAULT false,
  catalog_account_id BIGINT REFERENCES catalog_account(id),
  inventory_account_id BIGINT REFERENCES inventory_account(id)
);
CREATE INDEX hr_account_catalog_account_id_idx ON hr_account(catalog_account_id);
CREATE INDEX hr_account_inventory_account_id_idx ON hr_account(inventory_account_id);

CREATE TABLE finance_account (
  id           BIGSERIAL PRIMARY KEY,
  metadata_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  code_2 INTEGER NOT NULL DEFAULT 0,
  inventory_account_id BIGINT REFERENCES inventory_account(id),
  hr_account_id BIGINT REFERENCES hr_account(id)
);
CREATE INDEX finance_account_inventory_account_id_idx ON finance_account(inventory_account_id);
CREATE INDEX finance_account_hr_account_id_idx ON finance_account(hr_account_id);

CREATE TABLE crm_account (
  id           BIGSERIAL PRIMARY KEY,
  reference_1 INTEGER NOT NULL DEFAULT 0,
  ended_at_2 INTEGER NOT NULL DEFAULT 0,
  kind_3 TEXT,
  payload_4 INTEGER NOT NULL DEFAULT 0,
  ended_at_5 INTEGER NOT NULL DEFAULT 0,
  inventory_account_id BIGINT REFERENCES inventory_account(id),
  finance_account_id BIGINT REFERENCES finance_account(id)
);
CREATE INDEX crm_account_inventory_account_id_idx ON crm_account(inventory_account_id);
CREATE INDEX crm_account_finance_account_id_idx ON crm_account(finance_account_id);

CREATE TABLE support_account (
  id           BIGSERIAL PRIMARY KEY,
  kind_1 TEXT,
  weight_grams_2 NUMERIC(12,2),
  billing_account_id BIGINT REFERENCES billing_account(id),
  inventory_account_id BIGINT REFERENCES inventory_account(id)
);
CREATE INDEX support_account_billing_account_id_idx ON support_account(billing_account_id);
CREATE INDEX support_account_inventory_account_id_idx ON support_account(inventory_account_id);

CREATE TABLE logistics_account (
  id           BIGSERIAL PRIMARY KEY,
  unit_1 BIGINT,
  unit_2 TEXT,
  score_3 INTEGER NOT NULL DEFAULT 0,
  catalog_account_id BIGINT REFERENCES catalog_account(id),
  crm_account_id BIGINT REFERENCES crm_account(id)
);
CREATE INDEX logistics_account_catalog_account_id_idx ON logistics_account(catalog_account_id);
CREATE INDEX logistics_account_crm_account_id_idx ON logistics_account(crm_account_id);

CREATE TABLE audit_account (
  id           BIGSERIAL PRIMARY KEY,
  quantity_1 TEXT,
  ended_at_2 NUMERIC(12,2),
  metadata_3 INTEGER NOT NULL DEFAULT 0,
  inventory_account_id BIGINT REFERENCES inventory_account(id),
  finance_account_id BIGINT REFERENCES finance_account(id)
);
CREATE INDEX audit_account_inventory_account_id_idx ON audit_account(inventory_account_id);
CREATE INDEX audit_account_finance_account_id_idx ON audit_account(finance_account_id);

CREATE TABLE reporting_account (
  id           BIGSERIAL PRIMARY KEY,
  priority_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes_2 TEXT,
  reference_3 BIGINT,
  weight_grams_4 INTEGER NOT NULL DEFAULT 0,
  unit_5 TEXT,
  crm_account_id BIGINT REFERENCES crm_account(id),
  logistics_account_id BIGINT REFERENCES logistics_account(id)
);
CREATE INDEX reporting_account_crm_account_id_idx ON reporting_account(crm_account_id);
CREATE INDEX reporting_account_logistics_account_id_idx ON reporting_account(logistics_account_id);

CREATE TABLE identity_account (
  id           BIGSERIAL PRIMARY KEY,
  name_1 BOOLEAN NOT NULL DEFAULT false,
  notes_2 BIGINT,
  logistics_account_id BIGINT REFERENCES logistics_account(id),
  audit_account_id BIGINT REFERENCES audit_account(id)
);
CREATE INDEX identity_account_logistics_account_id_idx ON identity_account(logistics_account_id);
CREATE INDEX identity_account_audit_account_id_idx ON identity_account(audit_account_id);

CREATE TABLE payments_account (
  id           BIGSERIAL PRIMARY KEY,
  kind_1 BIGINT,
  ended_at_2 TEXT,
  notes_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  score_4 INTEGER NOT NULL DEFAULT 0,
  description_5 BIGINT,
  ended_at_6 TIMESTAMPTZ NOT NULL DEFAULT now(),
  billing_account_id BIGINT REFERENCES billing_account(id),
  reporting_account_id BIGINT REFERENCES reporting_account(id)
);
CREATE INDEX payments_account_billing_account_id_idx ON payments_account(billing_account_id);
CREATE INDEX payments_account_reporting_account_id_idx ON payments_account(reporting_account_id);

CREATE TABLE messaging_account (
  id           BIGSERIAL PRIMARY KEY,
  name_1 BIGINT,
  started_at_2 BIGINT,
  payload_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata_4 INTEGER NOT NULL DEFAULT 0,
  priority_5 INTEGER NOT NULL DEFAULT 0,
  score_6 BOOLEAN NOT NULL DEFAULT false,
  audit_account_id BIGINT REFERENCES audit_account(id),
  identity_account_id BIGINT REFERENCES identity_account(id)
);
CREATE INDEX messaging_account_audit_account_id_idx ON messaging_account(audit_account_id);
CREATE INDEX messaging_account_identity_account_id_idx ON messaging_account(identity_account_id);

CREATE TABLE documents_account (
  id           BIGSERIAL PRIMARY KEY,
  score_1 BOOLEAN NOT NULL DEFAULT false,
  reference_2 BOOLEAN NOT NULL DEFAULT false,
  description_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  finance_account_id BIGINT REFERENCES finance_account(id),
  identity_account_id BIGINT REFERENCES identity_account(id)
);
CREATE INDEX documents_account_finance_account_id_idx ON documents_account(finance_account_id);
CREATE INDEX documents_account_identity_account_id_idx ON documents_account(identity_account_id);

CREATE TABLE calendar_account (
  id           BIGSERIAL PRIMARY KEY,
  amount_cents_1 BOOLEAN NOT NULL DEFAULT false,
  ended_at_2 BIGINT,
  unit_3 INTEGER NOT NULL DEFAULT 0,
  inventory_account_id BIGINT REFERENCES inventory_account(id),
  crm_account_id BIGINT REFERENCES crm_account(id)
);
CREATE INDEX calendar_account_inventory_account_id_idx ON calendar_account(inventory_account_id);
CREATE INDEX calendar_account_crm_account_id_idx ON calendar_account(crm_account_id);

CREATE TABLE healthcare_account (
  id           BIGSERIAL PRIMARY KEY,
  external_id_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata_2 BIGINT,
  amount_cents_3 TEXT,
  amount_cents_4 INTEGER NOT NULL DEFAULT 0,
  external_id_5 TEXT,
  code_6 TEXT,
  support_account_id BIGINT REFERENCES support_account(id),
  calendar_account_id BIGINT REFERENCES calendar_account(id)
);
CREATE INDEX healthcare_account_support_account_id_idx ON healthcare_account(support_account_id);
CREATE INDEX healthcare_account_calendar_account_id_idx ON healthcare_account(calendar_account_id);

CREATE TABLE insurance_account (
  id           BIGSERIAL PRIMARY KEY,
  priority_1 NUMERIC(12,2),
  weight_grams_2 INTEGER NOT NULL DEFAULT 0,
  identity_account_id BIGINT REFERENCES identity_account(id),
  messaging_account_id BIGINT REFERENCES messaging_account(id)
);
CREATE INDEX insurance_account_identity_account_id_idx ON insurance_account(identity_account_id);
CREATE INDEX insurance_account_messaging_account_id_idx ON insurance_account(messaging_account_id);

CREATE TABLE research_account (
  id           BIGSERIAL PRIMARY KEY,
  status_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  weight_grams_2 TEXT,
  name_3 BIGINT,
  external_id_4 NUMERIC(12,2),
  payload_5 INTEGER NOT NULL DEFAULT 0,
  crm_account_id BIGINT REFERENCES crm_account(id),
  documents_account_id BIGINT REFERENCES documents_account(id)
);
CREATE INDEX research_account_crm_account_id_idx ON research_account(crm_account_id);
CREATE INDEX research_account_documents_account_id_idx ON research_account(documents_account_id);

CREATE TABLE content_account (
  id           BIGSERIAL PRIMARY KEY,
  quantity_1 BIGINT,
  payload_2 NUMERIC(12,2),
  documents_account_id BIGINT REFERENCES documents_account(id),
  calendar_account_id BIGINT REFERENCES calendar_account(id)
);
CREATE INDEX content_account_documents_account_id_idx ON content_account(documents_account_id);
CREATE INDEX content_account_calendar_account_id_idx ON content_account(calendar_account_id);

CREATE TABLE analytics_account (
  id           BIGSERIAL PRIMARY KEY,
  external_id_1 BOOLEAN NOT NULL DEFAULT false,
  quantity_2 BOOLEAN NOT NULL DEFAULT false,
  score_3 BIGINT,
  description_4 INTEGER NOT NULL DEFAULT 0,
  status_5 TEXT,
  billing_account_id BIGINT REFERENCES billing_account(id),
  healthcare_account_id BIGINT REFERENCES healthcare_account(id)
);
CREATE INDEX analytics_account_billing_account_id_idx ON analytics_account(billing_account_id);
CREATE INDEX analytics_account_healthcare_account_id_idx ON analytics_account(healthcare_account_id);

CREATE TABLE procurement_account (
  id           BIGSERIAL PRIMARY KEY,
  notes_1 INTEGER NOT NULL DEFAULT 0,
  metadata_2 BIGINT,
  reference_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  external_id_4 BIGINT,
  reporting_account_id BIGINT REFERENCES reporting_account(id),
  insurance_account_id BIGINT REFERENCES insurance_account(id)
);
CREATE INDEX procurement_account_reporting_account_id_idx ON procurement_account(reporting_account_id);
CREATE INDEX procurement_account_insurance_account_id_idx ON procurement_account(insurance_account_id);

CREATE TABLE warehouse_account (
  id           BIGSERIAL PRIMARY KEY,
  quantity_1 BIGINT,
  weight_grams_2 INTEGER NOT NULL DEFAULT 0,
  reference_3 INTEGER NOT NULL DEFAULT 0,
  reference_4 BIGINT,
  code_5 INTEGER NOT NULL DEFAULT 0,
  notes_6 TEXT,
  research_account_id BIGINT REFERENCES research_account(id),
  analytics_account_id BIGINT REFERENCES analytics_account(id)
);
CREATE INDEX warehouse_account_research_account_id_idx ON warehouse_account(research_account_id);
CREATE INDEX warehouse_account_analytics_account_id_idx ON warehouse_account(analytics_account_id);

CREATE TABLE fleet_account (
  id           BIGSERIAL PRIMARY KEY,
  code_1 NUMERIC(12,2),
  ended_at_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  name_3 BIGINT,
  finance_account_id BIGINT REFERENCES finance_account(id),
  research_account_id BIGINT REFERENCES research_account(id)
);
CREATE INDEX fleet_account_finance_account_id_idx ON fleet_account(finance_account_id);
CREATE INDEX fleet_account_research_account_id_idx ON fleet_account(research_account_id);

CREATE TABLE maintenance_account (
  id           BIGSERIAL PRIMARY KEY,
  priority_1 INTEGER NOT NULL DEFAULT 0,
  amount_cents_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  procurement_account_id BIGINT REFERENCES procurement_account(id),
  warehouse_account_id BIGINT REFERENCES warehouse_account(id)
);
CREATE INDEX maintenance_account_procurement_account_id_idx ON maintenance_account(procurement_account_id);
CREATE INDEX maintenance_account_warehouse_account_id_idx ON maintenance_account(warehouse_account_id);

CREATE TABLE legal_account (
  id           BIGSERIAL PRIMARY KEY,
  started_at_1 TEXT,
  description_2 BOOLEAN NOT NULL DEFAULT false,
  started_at_3 BIGINT,
  weight_grams_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  status_5 INTEGER NOT NULL DEFAULT 0,
  weight_grams_6 NUMERIC(12,2),
  insurance_account_id BIGINT REFERENCES insurance_account(id),
  analytics_account_id BIGINT REFERENCES analytics_account(id)
);
CREATE INDEX legal_account_insurance_account_id_idx ON legal_account(insurance_account_id);
CREATE INDEX legal_account_analytics_account_id_idx ON legal_account(analytics_account_id);

CREATE TABLE compliance_account (
  id           BIGSERIAL PRIMARY KEY,
  unit_1 INTEGER NOT NULL DEFAULT 0,
  notes_2 TEXT,
  procurement_account_id BIGINT REFERENCES procurement_account(id),
  warehouse_account_id BIGINT REFERENCES warehouse_account(id)
);
CREATE INDEX compliance_account_procurement_account_id_idx ON compliance_account(procurement_account_id);
CREATE INDEX compliance_account_warehouse_account_id_idx ON compliance_account(warehouse_account_id);

CREATE TABLE marketing_account (
  id           BIGSERIAL PRIMARY KEY,
  ended_at_1 INTEGER NOT NULL DEFAULT 0,
  started_at_2 NUMERIC(12,2),
  code_3 NUMERIC(12,2),
  calendar_account_id BIGINT REFERENCES calendar_account(id),
  content_account_id BIGINT REFERENCES content_account(id)
);
CREATE INDEX marketing_account_calendar_account_id_idx ON marketing_account(calendar_account_id);
CREATE INDEX marketing_account_content_account_id_idx ON marketing_account(content_account_id);

CREATE TABLE training_account (
  id           BIGSERIAL PRIMARY KEY,
  payload_1 BIGINT,
  ended_at_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  name_3 BIGINT,
  reference_4 BOOLEAN NOT NULL DEFAULT false,
  finance_account_id BIGINT REFERENCES finance_account(id),
  healthcare_account_id BIGINT REFERENCES healthcare_account(id)
);
CREATE INDEX training_account_finance_account_id_idx ON training_account(finance_account_id);
CREATE INDEX training_account_healthcare_account_id_idx ON training_account(healthcare_account_id);

CREATE TABLE vendor_account (
  id           BIGSERIAL PRIMARY KEY,
  name_1 TEXT,
  unit_2 TEXT,
  metadata_3 BIGINT,
  quantity_4 BIGINT,
  content_account_id BIGINT REFERENCES content_account(id),
  procurement_account_id BIGINT REFERENCES procurement_account(id)
);
CREATE INDEX vendor_account_content_account_id_idx ON vendor_account(content_account_id);
CREATE INDEX vendor_account_procurement_account_id_idx ON vendor_account(procurement_account_id);

CREATE TABLE product_account (
  id           BIGSERIAL PRIMARY KEY,
  started_at_1 BOOLEAN NOT NULL DEFAULT false,
  unit_2 BIGINT,
  crm_account_id BIGINT REFERENCES crm_account(id),
  vendor_account_id BIGINT REFERENCES vendor_account(id)
);
CREATE INDEX product_account_crm_account_id_idx ON product_account(crm_account_id);
CREATE INDEX product_account_vendor_account_id_idx ON product_account(vendor_account_id);

CREATE TABLE order_account (
  id           BIGSERIAL PRIMARY KEY,
  weight_grams_1 INTEGER NOT NULL DEFAULT 0,
  metadata_2 INTEGER NOT NULL DEFAULT 0,
  ended_at_3 INTEGER NOT NULL DEFAULT 0,
  score_4 INTEGER NOT NULL DEFAULT 0,
  payload_5 BIGINT,
  started_at_6 BOOLEAN NOT NULL DEFAULT false,
  crm_account_id BIGINT REFERENCES crm_account(id),
  product_account_id BIGINT REFERENCES product_account(id)
);
CREATE INDEX order_account_crm_account_id_idx ON order_account(crm_account_id);
CREATE INDEX order_account_product_account_id_idx ON order_account(product_account_id);

CREATE TABLE shipment_account (
  id           BIGSERIAL PRIMARY KEY,
  quantity_1 BOOLEAN NOT NULL DEFAULT false,
  notes_2 NUMERIC(12,2),
  logistics_account_id BIGINT REFERENCES logistics_account(id),
  marketing_account_id BIGINT REFERENCES marketing_account(id)
);
CREATE INDEX shipment_account_logistics_account_id_idx ON shipment_account(logistics_account_id);
CREATE INDEX shipment_account_marketing_account_id_idx ON shipment_account(marketing_account_id);

CREATE TABLE license_account (
  id           BIGSERIAL PRIMARY KEY,
  ended_at_1 INTEGER NOT NULL DEFAULT 0,
  status_2 BIGINT,
  training_account_id BIGINT REFERENCES training_account(id),
  order_account_id BIGINT REFERENCES order_account(id)
);
CREATE INDEX license_account_training_account_id_idx ON license_account(training_account_id);
CREATE INDEX license_account_order_account_id_idx ON license_account(order_account_id);

CREATE TABLE policy_account (
  id           BIGSERIAL PRIMARY KEY,
  priority_1 INTEGER NOT NULL DEFAULT 0,
  payload_2 INTEGER NOT NULL DEFAULT 0,
  score_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  identity_account_id BIGINT REFERENCES identity_account(id),
  vendor_account_id BIGINT REFERENCES vendor_account(id)
);
CREATE INDEX policy_account_identity_account_id_idx ON policy_account(identity_account_id);
CREATE INDEX policy_account_vendor_account_id_idx ON policy_account(vendor_account_id);

CREATE TABLE facility_account (
  id           BIGSERIAL PRIMARY KEY,
  kind_1 NUMERIC(12,2),
  amount_cents_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  external_id_3 TEXT,
  started_at_4 NUMERIC(12,2),
  ended_at_5 NUMERIC(12,2),
  ended_at_6 BIGINT,
  order_account_id BIGINT REFERENCES order_account(id),
  license_account_id BIGINT REFERENCES license_account(id)
);
CREATE INDEX facility_account_order_account_id_idx ON facility_account(order_account_id);
CREATE INDEX facility_account_license_account_id_idx ON facility_account(license_account_id);

CREATE TABLE room_account (
  id           BIGSERIAL PRIMARY KEY,
  weight_grams_1 TEXT,
  started_at_2 INTEGER NOT NULL DEFAULT 0,
  order_account_id BIGINT REFERENCES order_account(id),
  shipment_account_id BIGINT REFERENCES shipment_account(id)
);
CREATE INDEX room_account_order_account_id_idx ON room_account(order_account_id);
CREATE INDEX room_account_shipment_account_id_idx ON room_account(shipment_account_id);

CREATE TABLE asset_account (
  id           BIGSERIAL PRIMARY KEY,
  reference_1 TEXT,
  unit_2 BIGINT,
  score_3 BOOLEAN NOT NULL DEFAULT false,
  external_id_4 INTEGER NOT NULL DEFAULT 0,
  score_5 TIMESTAMPTZ NOT NULL DEFAULT now(),
  amount_cents_6 BIGINT,
  policy_account_id BIGINT REFERENCES policy_account(id),
  room_account_id BIGINT REFERENCES room_account(id)
);
CREATE INDEX asset_account_policy_account_id_idx ON asset_account(policy_account_id);
CREATE INDEX asset_account_room_account_id_idx ON asset_account(room_account_id);

CREATE TABLE booking_account (
  id           BIGSERIAL PRIMARY KEY,
  metadata_1 BIGINT,
  priority_2 BIGINT,
  external_id_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  license_account_id BIGINT REFERENCES license_account(id),
  asset_account_id BIGINT REFERENCES asset_account(id)
);
CREATE INDEX booking_account_license_account_id_idx ON booking_account(license_account_id);
CREATE INDEX booking_account_asset_account_id_idx ON booking_account(asset_account_id);

CREATE TABLE survey_account (
  id           BIGSERIAL PRIMARY KEY,
  quantity_1 BIGINT,
  quantity_2 INTEGER NOT NULL DEFAULT 0,
  payload_3 INTEGER NOT NULL DEFAULT 0,
  score_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at_5 TEXT,
  started_at_6 INTEGER NOT NULL DEFAULT 0,
  finance_account_id BIGINT REFERENCES finance_account(id),
  asset_account_id BIGINT REFERENCES asset_account(id)
);
CREATE INDEX survey_account_finance_account_id_idx ON survey_account(finance_account_id);
CREATE INDEX survey_account_asset_account_id_idx ON survey_account(asset_account_id);

CREATE TABLE campaign_account (
  id           BIGSERIAL PRIMARY KEY,
  kind_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  payload_2 NUMERIC(12,2),
  unit_3 TEXT,
  procurement_account_id BIGINT REFERENCES procurement_account(id),
  survey_account_id BIGINT REFERENCES survey_account(id)
);
CREATE INDEX campaign_account_procurement_account_id_idx ON campaign_account(procurement_account_id);
CREATE INDEX campaign_account_survey_account_id_idx ON campaign_account(survey_account_id);

CREATE TABLE ticket_account (
  id           BIGSERIAL PRIMARY KEY,
  metadata_1 BOOLEAN NOT NULL DEFAULT false,
  code_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  priority_3 BIGINT,
  metadata_4 INTEGER NOT NULL DEFAULT 0,
  crm_account_id BIGINT REFERENCES crm_account(id),
  room_account_id BIGINT REFERENCES room_account(id)
);
CREATE INDEX ticket_account_crm_account_id_idx ON ticket_account(crm_account_id);
CREATE INDEX ticket_account_room_account_id_idx ON ticket_account(room_account_id);

CREATE TABLE incident_account (
  id           BIGSERIAL PRIMARY KEY,
  unit_1 NUMERIC(12,2),
  description_2 TEXT,
  weight_grams_3 INTEGER NOT NULL DEFAULT 0,
  research_account_id BIGINT REFERENCES research_account(id),
  room_account_id BIGINT REFERENCES room_account(id)
);
CREATE INDEX incident_account_research_account_id_idx ON incident_account(research_account_id);
CREATE INDEX incident_account_room_account_id_idx ON incident_account(room_account_id);

CREATE TABLE request_account (
  id           BIGSERIAL PRIMARY KEY,
  notes_1 NUMERIC(12,2),
  description_2 NUMERIC(12,2),
  code_3 TEXT,
  amount_cents_4 TEXT,
  product_account_id BIGINT REFERENCES product_account(id),
  incident_account_id BIGINT REFERENCES incident_account(id)
);
CREATE INDEX request_account_product_account_id_idx ON request_account(product_account_id);
CREATE INDEX request_account_incident_account_id_idx ON request_account(incident_account_id);

CREATE TABLE batch_account (
  id           BIGSERIAL PRIMARY KEY,
  amount_cents_1 BOOLEAN NOT NULL DEFAULT false,
  priority_2 NUMERIC(12,2),
  score_3 NUMERIC(12,2),
  training_account_id BIGINT REFERENCES training_account(id),
  request_account_id BIGINT REFERENCES request_account(id)
);
CREATE INDEX batch_account_training_account_id_idx ON batch_account(training_account_id);
CREATE INDEX batch_account_request_account_id_idx ON batch_account(request_account_id);

CREATE TABLE lot_account (
  id           BIGSERIAL PRIMARY KEY,
  reference_1 INTEGER NOT NULL DEFAULT 0,
  amount_cents_2 BOOLEAN NOT NULL DEFAULT false,
  billing_account_id BIGINT REFERENCES billing_account(id),
  facility_account_id BIGINT REFERENCES facility_account(id)
);
CREATE INDEX lot_account_billing_account_id_idx ON lot_account(billing_account_id);
CREATE INDEX lot_account_facility_account_id_idx ON lot_account(facility_account_id);

CREATE TABLE serial_account (
  id           BIGSERIAL PRIMARY KEY,
  metadata_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  description_2 BIGINT,
  description_3 BOOLEAN NOT NULL DEFAULT false,
  code_4 NUMERIC(12,2),
  code_5 BOOLEAN NOT NULL DEFAULT false,
  ticket_account_id BIGINT REFERENCES ticket_account(id),
  batch_account_id BIGINT REFERENCES batch_account(id)
);
CREATE INDEX serial_account_ticket_account_id_idx ON serial_account(ticket_account_id);
CREATE INDEX serial_account_batch_account_id_idx ON serial_account(batch_account_id);

CREATE TABLE voucher_account (
  id           BIGSERIAL PRIMARY KEY,
  weight_grams_1 TEXT,
  kind_2 TEXT,
  status_3 NUMERIC(12,2),
  insurance_account_id BIGINT REFERENCES insurance_account(id),
  incident_account_id BIGINT REFERENCES incident_account(id)
);
CREATE INDEX voucher_account_insurance_account_id_idx ON voucher_account(insurance_account_id);
CREATE INDEX voucher_account_incident_account_id_idx ON voucher_account(incident_account_id);

CREATE TABLE credit_account (
  id           BIGSERIAL PRIMARY KEY,
  priority_1 BOOLEAN NOT NULL DEFAULT false,
  metadata_2 NUMERIC(12,2),
  marketing_account_id BIGINT REFERENCES marketing_account(id),
  asset_account_id BIGINT REFERENCES asset_account(id)
);
CREATE INDEX credit_account_marketing_account_id_idx ON credit_account(marketing_account_id);
CREATE INDEX credit_account_asset_account_id_idx ON credit_account(asset_account_id);

CREATE TABLE invoice_account (
  id           BIGSERIAL PRIMARY KEY,
  status_1 INTEGER NOT NULL DEFAULT 0,
  external_id_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  description_3 INTEGER NOT NULL DEFAULT 0,
  status_4 TEXT,
  metadata_5 BIGINT,
  unit_6 TEXT,
  logistics_account_id BIGINT REFERENCES logistics_account(id),
  batch_account_id BIGINT REFERENCES batch_account(id)
);
CREATE INDEX invoice_account_logistics_account_id_idx ON invoice_account(logistics_account_id);
CREATE INDEX invoice_account_batch_account_id_idx ON invoice_account(batch_account_id);

CREATE TABLE payment_account (
  id           BIGSERIAL PRIMARY KEY,
  metadata_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  kind_2 TEXT,
  lot_account_id BIGINT REFERENCES lot_account(id),
  voucher_account_id BIGINT REFERENCES voucher_account(id)
);
CREATE INDEX payment_account_lot_account_id_idx ON payment_account(lot_account_id);
CREATE INDEX payment_account_voucher_account_id_idx ON payment_account(voucher_account_id);

CREATE TABLE refund_account (
  id           BIGSERIAL PRIMARY KEY,
  score_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  status_2 NUMERIC(12,2),
  weight_grams_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  asset_account_id BIGINT REFERENCES asset_account(id),
  invoice_account_id BIGINT REFERENCES invoice_account(id)
);
CREATE INDEX refund_account_asset_account_id_idx ON refund_account(asset_account_id);
CREATE INDEX refund_account_invoice_account_id_idx ON refund_account(invoice_account_id);

CREATE TABLE claim_account (
  id           BIGSERIAL PRIMARY KEY,
  reference_1 BOOLEAN NOT NULL DEFAULT false,
  notes_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  quantity_3 INTEGER NOT NULL DEFAULT 0,
  inventory_account_id BIGINT REFERENCES inventory_account(id),
  credit_account_id BIGINT REFERENCES credit_account(id)
);
CREATE INDEX claim_account_inventory_account_id_idx ON claim_account(inventory_account_id);
CREATE INDEX claim_account_credit_account_id_idx ON claim_account(credit_account_id);

CREATE TABLE chart_account (
  id           BIGSERIAL PRIMARY KEY,
  notes_1 BIGINT,
  reference_2 TEXT,
  name_3 TEXT,
  score_4 TEXT,
  identity_account_id BIGINT REFERENCES identity_account(id),
  booking_account_id BIGINT REFERENCES booking_account(id)
);
CREATE INDEX chart_account_identity_account_id_idx ON chart_account(identity_account_id);
CREATE INDEX chart_account_booking_account_id_idx ON chart_account(booking_account_id);

CREATE TABLE lab_account (
  id           BIGSERIAL PRIMARY KEY,
  notes_1 INTEGER NOT NULL DEFAULT 0,
  kind_2 NUMERIC(12,2),
  reference_3 BIGINT,
  amount_cents_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  payment_account_id BIGINT REFERENCES payment_account(id),
  claim_account_id BIGINT REFERENCES claim_account(id)
);
CREATE INDEX lab_account_payment_account_id_idx ON lab_account(payment_account_id);
CREATE INDEX lab_account_claim_account_id_idx ON lab_account(claim_account_id);

CREATE TABLE imaging_account (
  id           BIGSERIAL PRIMARY KEY,
  quantity_1 NUMERIC(12,2),
  kind_2 NUMERIC(12,2),
  score_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at_4 NUMERIC(12,2),
  payments_account_id BIGINT REFERENCES payments_account(id),
  chart_account_id BIGINT REFERENCES chart_account(id)
);
CREATE INDEX imaging_account_payments_account_id_idx ON imaging_account(payments_account_id);
CREATE INDEX imaging_account_chart_account_id_idx ON imaging_account(chart_account_id);

CREATE TABLE prescription_account (
  id           BIGSERIAL PRIMARY KEY,
  kind_1 INTEGER NOT NULL DEFAULT 0,
  kind_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  training_account_id BIGINT REFERENCES training_account(id),
  refund_account_id BIGINT REFERENCES refund_account(id)
);
CREATE INDEX prescription_account_training_account_id_idx ON prescription_account(training_account_id);
CREATE INDEX prescription_account_refund_account_id_idx ON prescription_account(refund_account_id);

CREATE TABLE dose_account (
  id           BIGSERIAL PRIMARY KEY,
  priority_1 INTEGER NOT NULL DEFAULT 0,
  amount_cents_2 TEXT,
  kind_3 BIGINT,
  quantity_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  order_account_id BIGINT REFERENCES order_account(id),
  facility_account_id BIGINT REFERENCES facility_account(id)
);
CREATE INDEX dose_account_order_account_id_idx ON dose_account(order_account_id);
CREATE INDEX dose_account_facility_account_id_idx ON dose_account(facility_account_id);

CREATE TABLE patient_account (
  id           BIGSERIAL PRIMARY KEY,
  metadata_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  name_2 NUMERIC(12,2),
  payments_account_id BIGINT REFERENCES payments_account(id),
  booking_account_id BIGINT REFERENCES booking_account(id)
);
CREATE INDEX patient_account_payments_account_id_idx ON patient_account(payments_account_id);
CREATE INDEX patient_account_booking_account_id_idx ON patient_account(booking_account_id);

CREATE TABLE provider_account (
  id           BIGSERIAL PRIMARY KEY,
  description_1 BIGINT,
  status_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  description_3 INTEGER NOT NULL DEFAULT 0,
  unit_4 INTEGER NOT NULL DEFAULT 0,
  imaging_account_id BIGINT REFERENCES imaging_account(id),
  patient_account_id BIGINT REFERENCES patient_account(id)
);
CREATE INDEX provider_account_imaging_account_id_idx ON provider_account(imaging_account_id);
CREATE INDEX provider_account_patient_account_id_idx ON provider_account(patient_account_id);

CREATE TABLE practitioner_account (
  id           BIGSERIAL PRIMARY KEY,
  started_at_1 BIGINT,
  code_2 INTEGER NOT NULL DEFAULT 0,
  amount_cents_3 NUMERIC(12,2),
  quantity_4 TEXT,
  notes_5 TEXT,
  code_6 INTEGER NOT NULL DEFAULT 0,
  imaging_account_id BIGINT REFERENCES imaging_account(id),
  patient_account_id BIGINT REFERENCES patient_account(id)
);
CREATE INDEX practitioner_account_imaging_account_id_idx ON practitioner_account(imaging_account_id);
CREATE INDEX practitioner_account_patient_account_id_idx ON practitioner_account(patient_account_id);

CREATE TABLE encounter_account (
  id           BIGSERIAL PRIMARY KEY,
  score_1 INTEGER NOT NULL DEFAULT 0,
  quantity_2 INTEGER NOT NULL DEFAULT 0,
  kind_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  unit_4 TEXT,
  asset_account_id BIGINT REFERENCES asset_account(id),
  dose_account_id BIGINT REFERENCES dose_account(id)
);
CREATE INDEX encounter_account_asset_account_id_idx ON encounter_account(asset_account_id);
CREATE INDEX encounter_account_dose_account_id_idx ON encounter_account(dose_account_id);

CREATE TABLE diagnosis_account (
  id           BIGSERIAL PRIMARY KEY,
  metadata_1 NUMERIC(12,2),
  description_2 INTEGER NOT NULL DEFAULT 0,
  payload_3 TEXT,
  code_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  dose_account_id BIGINT REFERENCES dose_account(id),
  encounter_account_id BIGINT REFERENCES encounter_account(id)
);
CREATE INDEX diagnosis_account_dose_account_id_idx ON diagnosis_account(dose_account_id);
CREATE INDEX diagnosis_account_encounter_account_id_idx ON diagnosis_account(encounter_account_id);

CREATE TABLE procedure_account (
  id           BIGSERIAL PRIMARY KEY,
  reference_1 INTEGER NOT NULL DEFAULT 0,
  external_id_2 BIGINT,
  license_account_id BIGINT REFERENCES license_account(id),
  lab_account_id BIGINT REFERENCES lab_account(id)
);
CREATE INDEX procedure_account_license_account_id_idx ON procedure_account(license_account_id);
CREATE INDEX procedure_account_lab_account_id_idx ON procedure_account(lab_account_id);

CREATE TABLE observation_account (
  id           BIGSERIAL PRIMARY KEY,
  score_1 INTEGER NOT NULL DEFAULT 0,
  external_id_2 TEXT,
  priority_3 BIGINT,
  room_account_id BIGINT REFERENCES room_account(id),
  procedure_account_id BIGINT REFERENCES procedure_account(id)
);
CREATE INDEX observation_account_room_account_id_idx ON observation_account(room_account_id);
CREATE INDEX observation_account_procedure_account_id_idx ON observation_account(procedure_account_id);

CREATE TABLE specimen_account (
  id           BIGSERIAL PRIMARY KEY,
  external_id_1 BOOLEAN NOT NULL DEFAULT false,
  kind_2 NUMERIC(12,2),
  notes_3 NUMERIC(12,2),
  voucher_account_id BIGINT REFERENCES voucher_account(id),
  procedure_account_id BIGINT REFERENCES procedure_account(id)
);
CREATE INDEX specimen_account_voucher_account_id_idx ON specimen_account(voucher_account_id);
CREATE INDEX specimen_account_procedure_account_id_idx ON specimen_account(procedure_account_id);

CREATE TABLE allergy_account (
  id           BIGSERIAL PRIMARY KEY,
  notes_1 BOOLEAN NOT NULL DEFAULT false,
  weight_grams_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  description_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata_4 NUMERIC(12,2),
  audit_account_id BIGINT REFERENCES audit_account(id),
  practitioner_account_id BIGINT REFERENCES practitioner_account(id)
);
CREATE INDEX allergy_account_audit_account_id_idx ON allergy_account(audit_account_id);
CREATE INDEX allergy_account_practitioner_account_id_idx ON allergy_account(practitioner_account_id);

CREATE TABLE immunization_account (
  id           BIGSERIAL PRIMARY KEY,
  metadata_1 TEXT,
  code_2 BIGINT,
  priority_3 BIGINT,
  specimen_account_id BIGINT REFERENCES specimen_account(id),
  allergy_account_id BIGINT REFERENCES allergy_account(id)
);
CREATE INDEX immunization_account_specimen_account_id_idx ON immunization_account(specimen_account_id);
CREATE INDEX immunization_account_allergy_account_id_idx ON immunization_account(allergy_account_id);

CREATE TABLE medication_account (
  id           BIGSERIAL PRIMARY KEY,
  score_1 INTEGER NOT NULL DEFAULT 0,
  amount_cents_2 BIGINT,
  ended_at_3 INTEGER NOT NULL DEFAULT 0,
  refund_account_id BIGINT REFERENCES refund_account(id),
  prescription_account_id BIGINT REFERENCES prescription_account(id)
);
CREATE INDEX medication_account_refund_account_id_idx ON medication_account(refund_account_id);
CREATE INDEX medication_account_prescription_account_id_idx ON medication_account(prescription_account_id);

CREATE TABLE appointment_account (
  id           BIGSERIAL PRIMARY KEY,
  description_1 NUMERIC(12,2),
  unit_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at_3 INTEGER NOT NULL DEFAULT 0,
  reference_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  claim_account_id BIGINT REFERENCES claim_account(id),
  observation_account_id BIGINT REFERENCES observation_account(id)
);
CREATE INDEX appointment_account_claim_account_id_idx ON appointment_account(claim_account_id);
CREATE INDEX appointment_account_observation_account_id_idx ON appointment_account(observation_account_id);

CREATE TABLE referral_account (
  id           BIGSERIAL PRIMARY KEY,
  external_id_1 TEXT,
  ended_at_2 TEXT,
  amount_cents_3 BIGINT,
  ended_at_4 BIGINT,
  lot_account_id BIGINT REFERENCES lot_account(id),
  payment_account_id BIGINT REFERENCES payment_account(id)
);
CREATE INDEX referral_account_lot_account_id_idx ON referral_account(lot_account_id);
CREATE INDEX referral_account_payment_account_id_idx ON referral_account(payment_account_id);

CREATE TABLE authorization_account (
  id           BIGSERIAL PRIMARY KEY,
  started_at_1 NUMERIC(12,2),
  quantity_2 NUMERIC(12,2),
  incident_account_id BIGINT REFERENCES incident_account(id),
  medication_account_id BIGINT REFERENCES medication_account(id)
);
CREATE INDEX authorization_account_incident_account_id_idx ON authorization_account(incident_account_id);
CREATE INDEX authorization_account_medication_account_id_idx ON authorization_account(medication_account_id);

CREATE TABLE coverage_account (
  id           BIGSERIAL PRIMARY KEY,
  code_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  code_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  unit_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  legal_account_id BIGINT REFERENCES legal_account(id),
  authorization_account_id BIGINT REFERENCES authorization_account(id)
);
CREATE INDEX coverage_account_legal_account_id_idx ON coverage_account(legal_account_id);
CREATE INDEX coverage_account_authorization_account_id_idx ON coverage_account(authorization_account_id);

CREATE TABLE enrollment_account (
  id           BIGSERIAL PRIMARY KEY,
  description_1 NUMERIC(12,2),
  notes_2 BIGINT,
  payload_3 INTEGER NOT NULL DEFAULT 0,
  score_4 INTEGER NOT NULL DEFAULT 0,
  started_at_5 BIGINT,
  booking_account_id BIGINT REFERENCES booking_account(id),
  refund_account_id BIGINT REFERENCES refund_account(id)
);
CREATE INDEX enrollment_account_booking_account_id_idx ON enrollment_account(booking_account_id);
CREATE INDEX enrollment_account_refund_account_id_idx ON enrollment_account(refund_account_id);

CREATE TABLE member_account (
  id           BIGSERIAL PRIMARY KEY,
  priority_1 NUMERIC(12,2),
  notes_2 TEXT,
  external_id_3 BOOLEAN NOT NULL DEFAULT false,
  weight_grams_4 BOOLEAN NOT NULL DEFAULT false,
  code_5 BOOLEAN NOT NULL DEFAULT false,
  external_id_6 TEXT,
  analytics_account_id BIGINT REFERENCES analytics_account(id),
  appointment_account_id BIGINT REFERENCES appointment_account(id)
);
CREATE INDEX member_account_analytics_account_id_idx ON member_account(analytics_account_id);
CREATE INDEX member_account_appointment_account_id_idx ON member_account(appointment_account_id);

CREATE TABLE dependent_account (
  id           BIGSERIAL PRIMARY KEY,
  score_1 INTEGER NOT NULL DEFAULT 0,
  quantity_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  weight_grams_3 BIGINT,
  amount_cents_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at_5 TIMESTAMPTZ NOT NULL DEFAULT now(),
  insurance_account_id BIGINT REFERENCES insurance_account(id),
  appointment_account_id BIGINT REFERENCES appointment_account(id)
);
CREATE INDEX dependent_account_insurance_account_id_idx ON dependent_account(insurance_account_id);
CREATE INDEX dependent_account_appointment_account_id_idx ON dependent_account(appointment_account_id);

CREATE TABLE billing_item (
  id           BIGSERIAL PRIMARY KEY,
  status_1 BOOLEAN NOT NULL DEFAULT false,
  quantity_2 TEXT,
  metadata_3 BOOLEAN NOT NULL DEFAULT false,
  started_at_4 BOOLEAN NOT NULL DEFAULT false,
  status_5 BOOLEAN NOT NULL DEFAULT false,
  prescription_account_id BIGINT REFERENCES prescription_account(id),
  enrollment_account_id BIGINT REFERENCES enrollment_account(id)
);
CREATE INDEX billing_item_prescription_account_id_idx ON billing_item(prescription_account_id);
CREATE INDEX billing_item_enrollment_account_id_idx ON billing_item(enrollment_account_id);

CREATE TABLE catalog_item (
  id           BIGSERIAL PRIMARY KEY,
  priority_1 INTEGER NOT NULL DEFAULT 0,
  external_id_2 TEXT,
  external_id_3 NUMERIC(12,2),
  member_account_id BIGINT REFERENCES member_account(id),
  billing_item_id BIGINT REFERENCES billing_item(id)
);
CREATE INDEX catalog_item_member_account_id_idx ON catalog_item(member_account_id);
CREATE INDEX catalog_item_billing_item_id_idx ON catalog_item(billing_item_id);

CREATE TABLE inventory_item (
  id           BIGSERIAL PRIMARY KEY,
  weight_grams_1 TEXT,
  score_2 NUMERIC(12,2),
  enrollment_account_id BIGINT REFERENCES enrollment_account(id),
  dependent_account_id BIGINT REFERENCES dependent_account(id)
);
CREATE INDEX inventory_item_enrollment_account_id_idx ON inventory_item(enrollment_account_id);
CREATE INDEX inventory_item_dependent_account_id_idx ON inventory_item(dependent_account_id);

CREATE TABLE hr_item (
  id           BIGSERIAL PRIMARY KEY,
  code_1 BOOLEAN NOT NULL DEFAULT false,
  amount_cents_2 BOOLEAN NOT NULL DEFAULT false,
  warehouse_account_id BIGINT REFERENCES warehouse_account(id),
  procedure_account_id BIGINT REFERENCES procedure_account(id)
);
CREATE INDEX hr_item_warehouse_account_id_idx ON hr_item(warehouse_account_id);
CREATE INDEX hr_item_procedure_account_id_idx ON hr_item(procedure_account_id);

CREATE TABLE finance_item (
  id           BIGSERIAL PRIMARY KEY,
  kind_1 TEXT,
  started_at_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  billing_item_id BIGINT REFERENCES billing_item(id),
  inventory_item_id BIGINT REFERENCES inventory_item(id)
);
CREATE INDEX finance_item_billing_item_id_idx ON finance_item(billing_item_id);
CREATE INDEX finance_item_inventory_item_id_idx ON finance_item(inventory_item_id);

CREATE TABLE crm_item (
  id           BIGSERIAL PRIMARY KEY,
  code_1 INTEGER NOT NULL DEFAULT 0,
  unit_2 TEXT,
  insurance_account_id BIGINT REFERENCES insurance_account(id),
  shipment_account_id BIGINT REFERENCES shipment_account(id)
);
CREATE INDEX crm_item_insurance_account_id_idx ON crm_item(insurance_account_id);
CREATE INDEX crm_item_shipment_account_id_idx ON crm_item(shipment_account_id);

CREATE TABLE support_item (
  id           BIGSERIAL PRIMARY KEY,
  name_1 TEXT,
  weight_grams_2 INTEGER NOT NULL DEFAULT 0,
  unit_3 INTEGER NOT NULL DEFAULT 0,
  metadata_4 TEXT,
  score_5 NUMERIC(12,2),
  reference_6 TEXT,
  insurance_account_id BIGINT REFERENCES insurance_account(id),
  catalog_item_id BIGINT REFERENCES catalog_item(id)
);
CREATE INDEX support_item_insurance_account_id_idx ON support_item(insurance_account_id);
CREATE INDEX support_item_catalog_item_id_idx ON support_item(catalog_item_id);

CREATE TABLE logistics_item (
  id           BIGSERIAL PRIMARY KEY,
  score_1 BOOLEAN NOT NULL DEFAULT false,
  code_2 NUMERIC(12,2),
  external_id_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  amount_cents_4 INTEGER NOT NULL DEFAULT 0,
  code_5 NUMERIC(12,2),
  crm_item_id BIGINT REFERENCES crm_item(id),
  support_item_id BIGINT REFERENCES support_item(id)
);
CREATE INDEX logistics_item_crm_item_id_idx ON logistics_item(crm_item_id);
CREATE INDEX logistics_item_support_item_id_idx ON logistics_item(support_item_id);

CREATE TABLE audit_item (
  id           BIGSERIAL PRIMARY KEY,
  quantity_1 BIGINT,
  status_2 BIGINT,
  hr_account_id BIGINT REFERENCES hr_account(id),
  encounter_account_id BIGINT REFERENCES encounter_account(id)
);
CREATE INDEX audit_item_hr_account_id_idx ON audit_item(hr_account_id);
CREATE INDEX audit_item_encounter_account_id_idx ON audit_item(encounter_account_id);

CREATE TABLE reporting_item (
  id           BIGSERIAL PRIMARY KEY,
  quantity_1 BIGINT,
  payload_2 BOOLEAN NOT NULL DEFAULT false,
  ended_at_3 NUMERIC(12,2),
  kind_4 NUMERIC(12,2),
  quantity_5 BIGINT,
  payload_6 BIGINT,
  support_item_id BIGINT REFERENCES support_item(id),
  audit_item_id BIGINT REFERENCES audit_item(id)
);
CREATE INDEX reporting_item_support_item_id_idx ON reporting_item(support_item_id);
CREATE INDEX reporting_item_audit_item_id_idx ON reporting_item(audit_item_id);

CREATE TABLE identity_item (
  id           BIGSERIAL PRIMARY KEY,
  weight_grams_1 NUMERIC(12,2),
  status_2 NUMERIC(12,2),
  description_3 INTEGER NOT NULL DEFAULT 0,
  payload_4 INTEGER NOT NULL DEFAULT 0,
  crm_item_id BIGINT REFERENCES crm_item(id),
  audit_item_id BIGINT REFERENCES audit_item(id)
);
CREATE INDEX identity_item_crm_item_id_idx ON identity_item(crm_item_id);
CREATE INDEX identity_item_audit_item_id_idx ON identity_item(audit_item_id);

CREATE TABLE payments_item (
  id           BIGSERIAL PRIMARY KEY,
  payload_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  amount_cents_2 INTEGER NOT NULL DEFAULT 0,
  payload_3 TEXT,
  claim_account_id BIGINT REFERENCES claim_account(id),
  practitioner_account_id BIGINT REFERENCES practitioner_account(id)
);
CREATE INDEX payments_item_claim_account_id_idx ON payments_item(claim_account_id);
CREATE INDEX payments_item_practitioner_account_id_idx ON payments_item(practitioner_account_id);

CREATE TABLE messaging_item (
  id           BIGSERIAL PRIMARY KEY,
  unit_1 NUMERIC(12,2),
  weight_grams_2 BIGINT,
  unit_3 BIGINT,
  started_at_4 BOOLEAN NOT NULL DEFAULT false,
  reference_5 BIGINT,
  legal_account_id BIGINT REFERENCES legal_account(id),
  diagnosis_account_id BIGINT REFERENCES diagnosis_account(id)
);
CREATE INDEX messaging_item_legal_account_id_idx ON messaging_item(legal_account_id);
CREATE INDEX messaging_item_diagnosis_account_id_idx ON messaging_item(diagnosis_account_id);

CREATE TABLE documents_item (
  id           BIGSERIAL PRIMARY KEY,
  status_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  reference_2 BOOLEAN NOT NULL DEFAULT false,
  priority_3 NUMERIC(12,2),
  payments_item_id BIGINT REFERENCES payments_item(id),
  messaging_item_id BIGINT REFERENCES messaging_item(id)
);
CREATE INDEX documents_item_payments_item_id_idx ON documents_item(payments_item_id);
CREATE INDEX documents_item_messaging_item_id_idx ON documents_item(messaging_item_id);

CREATE TABLE calendar_item (
  id           BIGSERIAL PRIMARY KEY,
  reference_1 BIGINT,
  weight_grams_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes_3 INTEGER NOT NULL DEFAULT 0,
  amount_cents_4 BOOLEAN NOT NULL DEFAULT false,
  name_5 BOOLEAN NOT NULL DEFAULT false,
  score_6 BIGINT,
  identity_item_id BIGINT REFERENCES identity_item(id),
  payments_item_id BIGINT REFERENCES payments_item(id)
);
CREATE INDEX calendar_item_identity_item_id_idx ON calendar_item(identity_item_id);
CREATE INDEX calendar_item_payments_item_id_idx ON calendar_item(payments_item_id);

CREATE TABLE healthcare_item (
  id           BIGSERIAL PRIMARY KEY,
  reference_1 TEXT,
  priority_2 BIGINT,
  practitioner_account_id BIGINT REFERENCES practitioner_account(id),
  calendar_item_id BIGINT REFERENCES calendar_item(id)
);
CREATE INDEX healthcare_item_practitioner_account_id_idx ON healthcare_item(practitioner_account_id);
CREATE INDEX healthcare_item_calendar_item_id_idx ON healthcare_item(calendar_item_id);

CREATE TABLE insurance_item (
  id           BIGSERIAL PRIMARY KEY,
  unit_1 BOOLEAN NOT NULL DEFAULT false,
  payload_2 BOOLEAN NOT NULL DEFAULT false,
  messaging_item_id BIGINT REFERENCES messaging_item(id),
  healthcare_item_id BIGINT REFERENCES healthcare_item(id)
);
CREATE INDEX insurance_item_messaging_item_id_idx ON insurance_item(messaging_item_id);
CREATE INDEX insurance_item_healthcare_item_id_idx ON insurance_item(healthcare_item_id);

CREATE TABLE research_item (
  id           BIGSERIAL PRIMARY KEY,
  weight_grams_1 INTEGER NOT NULL DEFAULT 0,
  unit_2 BOOLEAN NOT NULL DEFAULT false,
  ended_at_3 BOOLEAN NOT NULL DEFAULT false,
  payload_4 BOOLEAN NOT NULL DEFAULT false,
  insurance_account_id BIGINT REFERENCES insurance_account(id),
  documents_item_id BIGINT REFERENCES documents_item(id)
);
CREATE INDEX research_item_insurance_account_id_idx ON research_item(insurance_account_id);
CREATE INDEX research_item_documents_item_id_idx ON research_item(documents_item_id);

CREATE TABLE content_item (
  id           BIGSERIAL PRIMARY KEY,
  notes_1 INTEGER NOT NULL DEFAULT 0,
  unit_2 NUMERIC(12,2),
  started_at_3 BIGINT,
  amount_cents_4 NUMERIC(12,2),
  vendor_account_id BIGINT REFERENCES vendor_account(id),
  procedure_account_id BIGINT REFERENCES procedure_account(id)
);
CREATE INDEX content_item_vendor_account_id_idx ON content_item(vendor_account_id);
CREATE INDEX content_item_procedure_account_id_idx ON content_item(procedure_account_id);

CREATE TABLE analytics_item (
  id           BIGSERIAL PRIMARY KEY,
  unit_1 TEXT,
  status_2 BOOLEAN NOT NULL DEFAULT false,
  notes_3 TEXT,
  quantity_4 TEXT,
  status_5 NUMERIC(12,2),
  name_6 TIMESTAMPTZ NOT NULL DEFAULT now(),
  payments_account_id BIGINT REFERENCES payments_account(id),
  refund_account_id BIGINT REFERENCES refund_account(id)
);
CREATE INDEX analytics_item_payments_account_id_idx ON analytics_item(payments_account_id);
CREATE INDEX analytics_item_refund_account_id_idx ON analytics_item(refund_account_id);

CREATE TABLE procurement_item (
  id           BIGSERIAL PRIMARY KEY,
  started_at_1 TEXT,
  external_id_2 BOOLEAN NOT NULL DEFAULT false,
  unit_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  catalog_item_id BIGINT REFERENCES catalog_item(id),
  healthcare_item_id BIGINT REFERENCES healthcare_item(id)
);
CREATE INDEX procurement_item_catalog_item_id_idx ON procurement_item(catalog_item_id);
CREATE INDEX procurement_item_healthcare_item_id_idx ON procurement_item(healthcare_item_id);

CREATE TABLE warehouse_item (
  id           BIGSERIAL PRIMARY KEY,
  quantity_1 BOOLEAN NOT NULL DEFAULT false,
  priority_2 TEXT,
  priority_3 BOOLEAN NOT NULL DEFAULT false,
  ended_at_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  policy_account_id BIGINT REFERENCES policy_account(id),
  insurance_item_id BIGINT REFERENCES insurance_item(id)
);
CREATE INDEX warehouse_item_policy_account_id_idx ON warehouse_item(policy_account_id);
CREATE INDEX warehouse_item_insurance_item_id_idx ON warehouse_item(insurance_item_id);

CREATE TABLE fleet_item (
  id           BIGSERIAL PRIMARY KEY,
  started_at_1 TEXT,
  weight_grams_2 INTEGER NOT NULL DEFAULT 0,
  ended_at_3 BOOLEAN NOT NULL DEFAULT false,
  status_4 NUMERIC(12,2),
  external_id_5 NUMERIC(12,2),
  warehouse_account_id BIGINT REFERENCES warehouse_account(id),
  analytics_item_id BIGINT REFERENCES analytics_item(id)
);
CREATE INDEX fleet_item_warehouse_account_id_idx ON fleet_item(warehouse_account_id);
CREATE INDEX fleet_item_analytics_item_id_idx ON fleet_item(analytics_item_id);

CREATE TABLE maintenance_item (
  id           BIGSERIAL PRIMARY KEY,
  payload_1 NUMERIC(12,2),
  notes_2 TEXT,
  kind_3 NUMERIC(12,2),
  billing_account_id BIGINT REFERENCES billing_account(id),
  dose_account_id BIGINT REFERENCES dose_account(id)
);
CREATE INDEX maintenance_item_billing_account_id_idx ON maintenance_item(billing_account_id);
CREATE INDEX maintenance_item_dose_account_id_idx ON maintenance_item(dose_account_id);

CREATE TABLE legal_item (
  id           BIGSERIAL PRIMARY KEY,
  name_1 INTEGER NOT NULL DEFAULT 0,
  started_at_2 TEXT,
  payload_3 NUMERIC(12,2),
  metadata_4 INTEGER NOT NULL DEFAULT 0,
  claim_account_id BIGINT REFERENCES claim_account(id),
  procurement_item_id BIGINT REFERENCES procurement_item(id)
);
CREATE INDEX legal_item_claim_account_id_idx ON legal_item(claim_account_id);
CREATE INDEX legal_item_procurement_item_id_idx ON legal_item(procurement_item_id);

CREATE TABLE compliance_item (
  id           BIGSERIAL PRIMARY KEY,
  notes_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata_2 NUMERIC(12,2),
  weight_grams_3 INTEGER NOT NULL DEFAULT 0,
  claim_account_id BIGINT REFERENCES claim_account(id),
  chart_account_id BIGINT REFERENCES chart_account(id)
);
CREATE INDEX compliance_item_claim_account_id_idx ON compliance_item(claim_account_id);
CREATE INDEX compliance_item_chart_account_id_idx ON compliance_item(chart_account_id);

CREATE TABLE marketing_item (
  id           BIGSERIAL PRIMARY KEY,
  code_1 TEXT,
  kind_2 NUMERIC(12,2),
  kind_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  amount_cents_4 BIGINT,
  identity_account_id BIGINT REFERENCES identity_account(id),
  lab_account_id BIGINT REFERENCES lab_account(id)
);
CREATE INDEX marketing_item_identity_account_id_idx ON marketing_item(identity_account_id);
CREATE INDEX marketing_item_lab_account_id_idx ON marketing_item(lab_account_id);

CREATE TABLE training_item (
  id           BIGSERIAL PRIMARY KEY,
  weight_grams_1 BIGINT,
  ended_at_2 NUMERIC(12,2),
  priority_3 NUMERIC(12,2),
  product_account_id BIGINT REFERENCES product_account(id),
  encounter_account_id BIGINT REFERENCES encounter_account(id)
);
CREATE INDEX training_item_product_account_id_idx ON training_item(product_account_id);
CREATE INDEX training_item_encounter_account_id_idx ON training_item(encounter_account_id);

CREATE TABLE vendor_item (
  id           BIGSERIAL PRIMARY KEY,
  payload_1 INTEGER NOT NULL DEFAULT 0,
  description_2 BIGINT,
  notes_3 BIGINT,
  unit_4 TEXT,
  payload_5 TEXT,
  ended_at_6 NUMERIC(12,2),
  reporting_account_id BIGINT REFERENCES reporting_account(id),
  patient_account_id BIGINT REFERENCES patient_account(id)
);
CREATE INDEX vendor_item_reporting_account_id_idx ON vendor_item(reporting_account_id);
CREATE INDEX vendor_item_patient_account_id_idx ON vendor_item(patient_account_id);

CREATE TABLE product_item (
  id           BIGSERIAL PRIMARY KEY,
  started_at_1 BIGINT,
  quantity_2 BIGINT,
  kind_3 BOOLEAN NOT NULL DEFAULT false,
  name_4 TEXT,
  payload_5 BOOLEAN NOT NULL DEFAULT false,
  compliance_item_id BIGINT REFERENCES compliance_item(id),
  marketing_item_id BIGINT REFERENCES marketing_item(id)
);
CREATE INDEX product_item_compliance_item_id_idx ON product_item(compliance_item_id);
CREATE INDEX product_item_marketing_item_id_idx ON product_item(marketing_item_id);

CREATE TABLE order_item (
  id           BIGSERIAL PRIMARY KEY,
  started_at_1 INTEGER NOT NULL DEFAULT 0,
  description_2 BIGINT,
  score_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  marketing_item_id BIGINT REFERENCES marketing_item(id),
  training_item_id BIGINT REFERENCES training_item(id)
);
CREATE INDEX order_item_marketing_item_id_idx ON order_item(marketing_item_id);
CREATE INDEX order_item_training_item_id_idx ON order_item(training_item_id);

CREATE TABLE shipment_item (
  id           BIGSERIAL PRIMARY KEY,
  external_id_1 INTEGER NOT NULL DEFAULT 0,
  amount_cents_2 TEXT,
  quantity_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  description_4 BOOLEAN NOT NULL DEFAULT false,
  name_5 BIGINT,
  name_6 NUMERIC(12,2),
  marketing_item_id BIGINT REFERENCES marketing_item(id),
  order_item_id BIGINT REFERENCES order_item(id)
);
CREATE INDEX shipment_item_marketing_item_id_idx ON shipment_item(marketing_item_id);
CREATE INDEX shipment_item_order_item_id_idx ON shipment_item(order_item_id);

CREATE TABLE license_item (
  id           BIGSERIAL PRIMARY KEY,
  ended_at_1 NUMERIC(12,2),
  unit_2 BIGINT,
  unit_3 TEXT,
  payload_4 TEXT,
  weight_grams_5 TEXT,
  unit_6 TIMESTAMPTZ NOT NULL DEFAULT now(),
  payment_account_id BIGINT REFERENCES payment_account(id),
  order_item_id BIGINT REFERENCES order_item(id)
);
CREATE INDEX license_item_payment_account_id_idx ON license_item(payment_account_id);
CREATE INDEX license_item_order_item_id_idx ON license_item(order_item_id);

CREATE TABLE policy_item (
  id           BIGSERIAL PRIMARY KEY,
  external_id_1 BOOLEAN NOT NULL DEFAULT false,
  unit_2 BIGINT,
  batch_account_id BIGINT REFERENCES batch_account(id),
  order_item_id BIGINT REFERENCES order_item(id)
);
CREATE INDEX policy_item_batch_account_id_idx ON policy_item(batch_account_id);
CREATE INDEX policy_item_order_item_id_idx ON policy_item(order_item_id);

CREATE TABLE facility_item (
  id           BIGSERIAL PRIMARY KEY,
  kind_1 NUMERIC(12,2),
  ended_at_2 BOOLEAN NOT NULL DEFAULT false,
  score_3 NUMERIC(12,2),
  payload_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  kind_5 INTEGER NOT NULL DEFAULT 0,
  analytics_account_id BIGINT REFERENCES analytics_account(id),
  shipment_account_id BIGINT REFERENCES shipment_account(id)
);
CREATE INDEX facility_item_analytics_account_id_idx ON facility_item(analytics_account_id);
CREATE INDEX facility_item_shipment_account_id_idx ON facility_item(shipment_account_id);

CREATE TABLE room_item (
  id           BIGSERIAL PRIMARY KEY,
  weight_grams_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  unit_2 INTEGER NOT NULL DEFAULT 0,
  amount_cents_3 TEXT,
  weight_grams_4 TEXT,
  description_5 TIMESTAMPTZ NOT NULL DEFAULT now(),
  status_6 INTEGER NOT NULL DEFAULT 0,
  audit_item_id BIGINT REFERENCES audit_item(id),
  facility_item_id BIGINT REFERENCES facility_item(id)
);
CREATE INDEX room_item_audit_item_id_idx ON room_item(audit_item_id);
CREATE INDEX room_item_facility_item_id_idx ON room_item(facility_item_id);

CREATE TABLE asset_item (
  id           BIGSERIAL PRIMARY KEY,
  code_1 TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at_2 NUMERIC(12,2),
  calendar_item_id BIGINT REFERENCES calendar_item(id),
  policy_item_id BIGINT REFERENCES policy_item(id)
);
CREATE INDEX asset_item_calendar_item_id_idx ON asset_item(calendar_item_id);
CREATE INDEX asset_item_policy_item_id_idx ON asset_item(policy_item_id);

CREATE TABLE booking_item (
  id           BIGSERIAL PRIMARY KEY,
  unit_1 INTEGER NOT NULL DEFAULT 0,
  reference_2 BOOLEAN NOT NULL DEFAULT false,
  external_id_3 NUMERIC(12,2),
  description_4 TIMESTAMPTZ NOT NULL DEFAULT now(),
  status_5 INTEGER NOT NULL DEFAULT 0,
  amount_cents_6 TEXT,
  policy_account_id BIGINT REFERENCES policy_account(id),
  license_item_id BIGINT REFERENCES license_item(id)
);
CREATE INDEX booking_item_policy_account_id_idx ON booking_item(policy_account_id);
CREATE INDEX booking_item_license_item_id_idx ON booking_item(license_item_id);

CREATE TABLE survey_item (
  id           BIGSERIAL PRIMARY KEY,
  weight_grams_1 NUMERIC(12,2),
  started_at_2 INTEGER NOT NULL DEFAULT 0,
  status_3 TEXT,
  amount_cents_4 NUMERIC(12,2),
  procurement_account_id BIGINT REFERENCES procurement_account(id),
  training_account_id BIGINT REFERENCES training_account(id)
);
CREATE INDEX survey_item_procurement_account_id_idx ON survey_item(procurement_account_id);
CREATE INDEX survey_item_training_account_id_idx ON survey_item(training_account_id);

CREATE TABLE campaign_item (
  id           BIGSERIAL PRIMARY KEY,
  started_at_1 BOOLEAN NOT NULL DEFAULT false,
  status_2 NUMERIC(12,2),
  external_id_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  external_id_4 INTEGER NOT NULL DEFAULT 0,
  notes_5 INTEGER NOT NULL DEFAULT 0,
  code_6 BOOLEAN NOT NULL DEFAULT false,
  room_item_id BIGINT REFERENCES room_item(id),
  asset_item_id BIGINT REFERENCES asset_item(id)
);
CREATE INDEX campaign_item_room_item_id_idx ON campaign_item(room_item_id);
CREATE INDEX campaign_item_asset_item_id_idx ON campaign_item(asset_item_id);

CREATE TABLE ticket_item (
  id           BIGSERIAL PRIMARY KEY,
  notes_1 TEXT,
  priority_2 NUMERIC(12,2),
  ended_at_3 BIGINT,
  kind_4 TEXT,
  payload_5 BOOLEAN NOT NULL DEFAULT false,
  kind_6 BIGINT,
  booking_item_id BIGINT REFERENCES booking_item(id),
  survey_item_id BIGINT REFERENCES survey_item(id)
);
CREATE INDEX ticket_item_booking_item_id_idx ON ticket_item(booking_item_id);
CREATE INDEX ticket_item_survey_item_id_idx ON ticket_item(survey_item_id);

CREATE TABLE incident_item (
  id           BIGSERIAL PRIMARY KEY,
  reference_1 INTEGER NOT NULL DEFAULT 0,
  quantity_2 BOOLEAN NOT NULL DEFAULT false,
  kind_3 TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata_4 NUMERIC(12,2),
  ended_at_5 TEXT,
  vendor_item_id BIGINT REFERENCES vendor_item(id),
  campaign_item_id BIGINT REFERENCES campaign_item(id)
);
CREATE INDEX incident_item_vendor_item_id_idx ON incident_item(vendor_item_id);
CREATE INDEX incident_item_campaign_item_id_idx ON incident_item(campaign_item_id);

CREATE TABLE request_item (
  id           BIGSERIAL PRIMARY KEY,
  ended_at_1 BOOLEAN NOT NULL DEFAULT false,
  started_at_2 TIMESTAMPTZ NOT NULL DEFAULT now(),
  score_3 BOOLEAN NOT NULL DEFAULT false,
  unit_4 NUMERIC(12,2),
  code_5 INTEGER NOT NULL DEFAULT 0,
  booking_item_id BIGINT REFERENCES booking_item(id),
  ticket_item_id BIGINT REFERENCES ticket_item(id)
);
CREATE INDEX request_item_booking_item_id_idx ON request_item(booking_item_id);
CREATE INDEX request_item_ticket_item_id_idx ON request_item(ticket_item_id);

CREATE TABLE batch_item (
  id           BIGSERIAL PRIMARY KEY,
  description_1 NUMERIC(12,2),
  started_at_2 BOOLEAN NOT NULL DEFAULT false,
  code_3 INTEGER NOT NULL DEFAULT 0,
  code_4 INTEGER NOT NULL DEFAULT 0,
  amount_cents_5 TEXT,
  coverage_account_id BIGINT REFERENCES coverage_account(id),
  campaign_item_id BIGINT REFERENCES campaign_item(id)
);
CREATE INDEX batch_item_coverage_account_id_idx ON batch_item(coverage_account_id);
CREATE INDEX batch_item_campaign_item_id_idx ON batch_item(campaign_item_id);

CREATE TABLE lot_item (
  id           BIGSERIAL PRIMARY KEY,
  external_id_1 BOOLEAN NOT NULL DEFAULT false,
  amount_cents_2 BOOLEAN NOT NULL DEFAULT false,
  allergy_account_id BIGINT REFERENCES allergy_account(id),
  incident_item_id BIGINT REFERENCES incident_item(id)
);
CREATE INDEX lot_item_allergy_account_id_idx ON lot_item(allergy_account_id);
CREATE INDEX lot_item_incident_item_id_idx ON lot_item(incident_item_id);

COMMIT;
